[package]
name = "cadence"
version = "0.1.1"
description = "An Apple Music–style client for Navidrome"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "cadence_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
jsonwebtoken = "9"
base64 = "0.22"
tokio = { version = "1", features = ["sync"] }
souvlaki = "0.8"
window-vibrancy = "0.8"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
